const INCIDENTS_KEY='mineguard_incidents_v1',MONITOR_KEY='mineguard_monitoring_v1';
const demoIncidents=[
 {id:101,date:'2026-09-18T09:20',location:'Demonstration Site A',type:'Near miss',area:'Processing',severity:3,recurrence:2,control:'partial',review:'yes',summary:'Repeated equipment access concern identified during routine inspection.',lat:6.20,lng:-1.55,status:'Under review',assignee:'Mine Safety Officer'},
 {id:102,date:'2026-09-20T13:10',location:'River Monitoring Point B',type:'Environmental observation',area:'Water body',severity:2,recurrence:1,control:'yes',review:'yes',summary:'Unusual turbidity observation requires validated sampling and professional review.',lat:6.34,lng:-1.41,status:'Action assigned',assignee:'Environmental Officer'},
 {id:103,date:'2026-09-22T08:05',location:'Community Boundary C',type:'Community concern',area:'Community boundary',severity:2,recurrence:0,control:'partial',review:'yes',summary:'Dust concern reported at community level for investigation.',lat:6.12,lng:-1.68,status:'Open',assignee:'Community Relations Officer'},
 {id:104,date:'2026-09-23T15:40',location:'Rehabilitation Zone D',type:'Environmental observation',area:'Rehabilitation area',severity:1,recurrence:0,control:'yes',review:'no',summary:'Routine rehabilitation inspection recorded stable progress.',lat:6.43,lng:-1.73,status:'Closed',assignee:'Environmental Officer'}
];
const demoMonitoring=[{id:201,date:'2026-09-20',point:'River Monitoring Point B',indicator:'Turbidity',value:18,unit:'NTU',threshold:15,notes:'Illustrative threshold exceeded. Professional sampling review required.'},{id:202,date:'2026-09-22',point:'Processing Area 1',indicator:'Noise',value:76,unit:'dB',threshold:85,notes:'Demonstration value within illustrative review threshold.'}];
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch(e){return fallback}}
let incidents=load(INCIDENTS_KEY,demoIncidents),monitoring=load(MONITOR_KEY,demoMonitoring);
function save(){localStorage.setItem(INCIDENTS_KEY,JSON.stringify(incidents));localStorage.setItem(MONITOR_KEY,JSON.stringify(monitoring));renderAll()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function riskOf(x){let score=x.severity*18+x.recurrence*12+(x.control==='no'?22:x.control==='partial'?10:0)+(x.review==='yes'?8:0);return Math.min(100,score)}
function levelOf(x){const s=riskOf(x);return s>=65?'Priority':s>=35?'Review':'Routine'}
function badge(level){return `<span class="badge ${level.toLowerCase()}">${level}</span>`}
function tableEmpty(text){return `<div class="empty">${text}</div>`}
function renderOverview(){
 const priority=incidents.filter(x=>levelOf(x)==='Priority').length,open=incidents.filter(x=>x.status!=='Closed').length,over=monitoring.filter(x=>x.threshold&&x.value>x.threshold).length,closed=incidents.filter(x=>x.status==='Closed').length;
 kpis.innerHTML=[['Open cases',open],['Priority review',priority],['Monitoring alerts',over],['Actions closed',closed]].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
 const p=incidents.filter(x=>levelOf(x)!=='Routine');priorityCases.innerHTML=p.length?`<div class="table-wrap"><table><thead><tr><th>Location</th><th>Type</th><th>Level</th><th>Status</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(x.location)}</td><td>${esc(x.type)}</td><td>${badge(levelOf(x))}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No priority cases.');
 const counts={};incidents.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);const max=Math.max(1,...Object.values(counts));categoryBars.innerHTML=Object.entries(counts).map(([name,n])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar"><div style="width:${n/max*100}%"></div></div><b>${n}</b></div>`).join('');
 recentTable.innerHTML=incidents.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Location</th><th>Area</th><th>Priority</th><th>Action owner</th></tr></thead><tbody>${incidents.slice().reverse().slice(0,8).map(x=>`<tr><td>${x.date.slice(0,10)}</td><td>${esc(x.location)}</td><td>${esc(x.area)}</td><td>${badge(levelOf(x))}</td><td>${esc(x.assignee)}</td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No activity recorded.');
}
incidentForm.onsubmit=e=>{e.preventDefault();const item={id:Date.now(),date:occurredAt.value,location:locationName.value.trim(),type:reportType.value,area:area.value,severity:+severity.value,recurrence:+recurrence.value,control:control.value,review:reviewRequired.value,summary:summary.value.trim(),lat:gpsConsent.value==='yes'?+latitude.value||null:null,lng:gpsConsent.value==='yes'?+longitude.value||null:null,status:'Open',assignee:reviewRequired.value==='yes'?'Professional review queue':'Monitoring team'};incidents.push(item);save();saveResult.innerHTML=`<article class="card result-card"><strong>Report saved for review.</strong><p>${badge(levelOf(item))} Explainable score: ${riskOf(item)}/100</p><p>Contributors: observed severity, recurrence, control status and professional review requirement. This is decision support only.</p></article>`;e.target.reset();setDefaults()};
gpsBtn.onclick=()=>{if(gpsConsent.value!=='yes'){alert('Record location consent before GPS capture.');return}if(!navigator.geolocation){alert('GPS is not supported on this device.');return}gpsBtn.textContent='Capturing…';navigator.geolocation.getCurrentPosition(p=>{latitude.value=p.coords.latitude.toFixed(5);longitude.value=p.coords.longitude.toFixed(5);gpsBtn.textContent='Location captured'},()=>{gpsBtn.textContent='Capture location';alert('Location could not be captured. Check browser permission.')},{enableHighAccuracy:true,timeout:12000})};
monitorForm.onsubmit=e=>{e.preventDefault();monitoring.push({id:Date.now(),date:monitorDate.value,point:monitorPoint.value.trim(),indicator:indicator.value,value:+resultValue.value,unit:resultUnit.value.trim(),threshold:+threshold.value||null,notes:monitorNotes.value.trim()});save();e.target.reset();monitorDate.value=new Date().toISOString().slice(0,10)};
function renderMonitoring(){monitorTable.innerHTML=monitoring.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Point</th><th>Indicator</th><th>Result</th><th>Review threshold</th><th>Signal</th></tr></thead><tbody>${monitoring.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.point)}</td><td>${esc(x.indicator)}</td><td>${x.value} ${esc(x.unit)}</td><td>${x.threshold??'Not set'}</td><td>${x.threshold&&x.value>x.threshold?badge('Priority'):badge('Routine')}</td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No monitoring records.')}
function updateCase(id,key,value){const x=incidents.find(r=>r.id===id);if(x){x[key]=value;save()}}
function renderCases(){caseTable.innerHTML=incidents.length?`<div class="table-wrap"><table><thead><tr><th>Case</th><th>Location</th><th>Priority</th><th>Assigned role</th><th>Status</th></tr></thead><tbody>${incidents.slice().reverse().map(x=>`<tr><td>MG-${x.id}</td><td>${esc(x.location)}</td><td>${badge(levelOf(x))}</td><td><select onchange="updateCase(${x.id},'assignee',this.value)">${['Mine Safety Officer','Environmental Officer','Occupational Health Officer','Community Relations Officer','Management Review'].map(v=>`<option ${x.assignee===v?'selected':''}>${v}</option>`).join('')}</select></td><td><select onchange="updateCase(${x.id},'status',this.value)">${['Open','Under review','Action assigned','Closed'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No cases.')}
function renderMap(){const located=incidents.filter(x=>x.lat&&x.lng);mapBoard.innerHTML=located.map((x,i)=>`<button class="point ${levelOf(x).toLowerCase()}" style="left:${15+(i*31)%72}%;top:${16+(i*47)%70}%" title="${esc(x.location)} · ${levelOf(x)}" aria-label="${esc(x.location)} ${levelOf(x)}"></button>`).join('');mapList.innerHTML=located.length?located.map(x=>`<div class="location-item"><b>${esc(x.location)}</b><span>${esc(x.type)} · ${levelOf(x)} review signal</span></div>`).join(''):tableEmpty('Capture consent based coordinates to populate the map.')}
function monthRows(){return reportMonth.value?incidents.filter(x=>x.date.startsWith(reportMonth.value)):incidents}
function renderReport(){const rows=monthRows(),open=rows.filter(x=>x.status!=='Closed').length,priority=rows.filter(x=>levelOf(x)==='Priority').length,closed=rows.filter(x=>x.status==='Closed').length;reportOutput.innerHTML=`<p class="eyebrow">MineGuard Ghana · ${esc(reportMonth.value||'All periods')}</p><h2>Mining Safety and Environmental Intelligence Summary</h2><div class="report-grid"><div><b>${rows.length}</b><span>Reports</span></div><div><b>${open}</b><span>Open cases</span></div><div><b>${priority}</b><span>Priority reviews</span></div><div><b>${closed}</b><span>Closed actions</span></div></div><h3>Management interpretation</h3><p>${rows.length?'Records requiring priority review should be assessed by the assigned qualified professional. Trends are based on demonstration data and should be compared with validated operational and regulatory information.':'No reports were recorded for this period.'}</p><div class="notice">MineGuard provides explainable decision support. It does not determine legal liability, diagnose workers or replace professional safety and environmental assessment.</div>`}
generateReport.onclick=renderReport;printReport.onclick=()=>window.print();downloadCsv.onclick=()=>{const rows=monthRows(),head=['id','date','location','type','area','status','assignee'],csv=[head.join(','),...rows.map(x=>head.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`).join(','))].join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`mineguard-${reportMonth.value||'all'}.csv`;a.click();URL.revokeObjectURL(url)};
const roleRules={'Administrator':'Manage configuration, approved users, permissions and audit logs.','Occupational Health Officer':'Access authorized worker screening flags and health follow up without exposing records to unrelated roles.','Mine Safety Officer':'Review incidents, near misses, corrective actions and assigned safety cases.','Environmental Officer':'Manage approved monitoring measurements, alerts and environmental follow up.','Community Relations Officer':'View community concerns and aggregated environmental summaries for assigned areas.','Management Viewer':'View high level trends and action status without unnecessary individual information.','Data Analyst':'Access deidentified approved datasets and reporting tools.','Regulatory Observer':'View authorized summaries and submitted evidence within the agreed oversight scope.'};function renderRole(){roleSummary.innerHTML=`<strong>${esc(roleSelect.value)}</strong><p>${roleRules[roleSelect.value]}</p><p><b>Access principle:</b> assigned site, approved purpose and minimum necessary information.</p>`}roleSelect.onchange=renderRole;renderRole();
function renderAll(){renderOverview();renderMonitoring();renderCases();renderMap();renderReport()}
document.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.page).classList.add('active');pageTitle.textContent=btn.textContent.trim();scrollTo({top:0,behavior:'smooth'})});
function setDefaults(){occurredAt.value=new Date().toISOString().slice(0,16);monitorDate.value=new Date().toISOString().slice(0,10);reportMonth.value=new Date().toISOString().slice(0,7)}setDefaults();
function updateNetwork(){networkText.textContent=navigator.onLine?'Online':'Offline';networkDot.style.background=navigator.onLine?'#28a17f':'#c67b24'}addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);updateNetwork();
let installPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installBtn.hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
