from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "insights"
BASE = "https://kwaw-ebn.github.io/ebenezer-kwaw-personal-website"

PROJECTS = [
    dict(slug="eco-me-africa-digital-growth-strategy", title="Eco-Me Africa Digital Growth Strategy", category="Digital Marketing and Growth", image="eco-me-africa.png", source="https://drive.google.com/file/d/1mNIb5lM5uviq1tkP09OdEFDddj7SmXYB/view?usp=sharing", summary="A digital audit and growth strategy for a menstrual-health, sustainability and women’s-empowerment organization.", problem="The review identified opportunities around website performance, user experience, brand consistency, SEO visibility, digital storytelling, social proof, partnership presentation and conversion pathways.", strategy="Build one connected digital ecosystem around website optimization, content marketing, social storytelling, founder visibility, community engagement and partnership conversion.", execution=["Reviewed the website, Instagram, Facebook, blog and partnership presentation.", "Defined audiences across young women and girls, schools, health institutions, NGOs, donors, CSR partners and sustainability advocates.", "Developed content pillars for education, impact stories, product communication, founder and team content, and advocacy.", "Produced website-redesign, SEO, content-calendar and partnership recommendations."], result="The deliverable is a strategic transformation plan and implementation roadmap. It should be read as a proposed growth programme, not evidence that every recommendation has already been implemented or measured.", tools="Digital audit, audience analysis, competitor review, SEO research, content strategy and conversion planning", status="Strategy and audit case study"),
    dict(slug="gh-wheels-seo-wordpress-optimization", title="GH Wheels SEO and WordPress Optimization", category="SEO and Website Optimization", image="gh-wheels.png", source="https://ghwheels.seopracticehub.com/", source_label="Visit live website", evidence="Live project website", summary="A practical website and on-page SEO project focused on improving the structure, discoverability and user journey of an automotive platform.", problem="The project addressed low search visibility and the need for clearer content, metadata and page structure.", strategy="Improve the WordPress website around search intent, usable navigation and technically consistent on-page signals.", execution=["Reviewed the existing page structure and search presentation.", "Improved page titles, metadata and content organization.", "Applied keyword-led on-page optimization.", "Reviewed usability and the path visitors take through the website."], result="The live website demonstrates the implemented structure and optimization work. Long-term organic impact would require verified analytics, ranking history and conversion tracking, so this case study avoids claiming performance figures that are not documented.", tools="WordPress, keyword research, on-page SEO, metadata and content optimization", status="Live website project"),
    dict(slug="wonderbuild-seo-website-optimization", title="Wonderbuild SEO and Website Optimization", category="SEO and Web Development", image="wonderbuild-website.png", source="https://kwaw-ebn.github.io/Wonderbuild/", source_label="Open live website", evidence="Live GitHub Pages website", summary="A responsive website and SEO project designed to improve how Wonderbuild presents its interlocking-brick solutions and converts interest into enquiries.", problem="The original digital experience needed clearer content structure, improved usability and stronger discoverability.", strategy="Connect a cleaner information hierarchy with responsive design, search-friendly content and direct enquiry pathways.", execution=["Reorganized website content around the company’s services and customer questions.", "Improved page structure and readability.", "Built a responsive web experience for desktop and mobile use.", "Applied on-page SEO and clearer calls to action."], result="The deployed GitHub Pages website demonstrates the implementation. Search and commercial outcomes should be assessed through verified Search Console, analytics and enquiry data rather than assumed from deployment alone.", tools="HTML, CSS, responsive design, GitHub Pages and on-page SEO", status="Live website project"),
    dict(slug="m-kopa-seo-content-growth-system", title="M-KOPA SEO and Content Growth System", category="SEO and Content Strategy", image="m-kopa.png", source="https://drive.google.com/file/d/1BU7rvkyUD9r_a3YHUxVlZgXZrD4eImxj/view", summary="A portfolio strategy demonstrating how competitor intelligence and content systems can support organic acquisition for an African fintech brand.", problem="The case identified visibility, authority, acquisition and structural gaps, including weak rankings for high-intent searches, limited content coverage and fragmented internal linking.", strategy="Use competitor intelligence and keyword gaps to build an intent-led content engine connected to product and conversion pages.", execution=["Conducted competitor and keyword-gap analysis.", "Defined visibility, intent and conversion as the north-star measurement areas.", "Designed technical and on-page improvements covering headings, metadata, URLs, sitemaps, site speed, alt text and internal linking.", "Created a 90-day roadmap covering foundation work, content production, schema and authority building."], result="The project produced a scalable organic-growth roadmap and identified high-value search opportunities. It is a strategic portfolio case study and does not claim access to M-KOPA’s internal implementation or performance data.", tools="Ubersuggest, competitor analysis, keyword research, technical SEO, content clusters and internal linking", status="Independent strategy case study"),
    dict(slug="amplify-multi-client-digital-marketing", title="Multi-Client Digital Marketing at Amplify", category="Digital Marketing Operations", image="amplify-marketing.png", source="https://drive.google.com/file/d/1kUltXkpnOmGTzDoCuTqXIfyP7jHdUgX3/view?usp=sharing", summary="A results-focused portfolio covering local SEO, Google Business Profile management, paid search, paid social and agency content across six accounts.", problem="Service businesses needed stronger local visibility, maintained business profiles, search-demand capture, measurable advertising and a repeatable SEO review process.", strategy="Combine ongoing local presence management with paid acquisition, technical SEO checks and channel-specific content.", execution=["Managed work across Eveready Home Care, Savannah Place Assisted Living, Ville-Ann Janitorial, 1st Providence, New Era Homecare and Amplify Marketing Agency.", "Maintained Google Business Profiles, content and service information across client locations.", "Supported Google Ads and Meta Ads campaigns and tracked clicks, leads, conversions and cost indicators.", "Used Ubersuggest audits to prioritize technical and on-page SEO improvements."], result="The source portfolio reports 23 Meta leads in three days for New Era, 116 Google Ads clicks and seven conversions for Eveready over 30 days, 1,968 views on Amplify’s Business Profile, and on-page SEO scores between 75 and 92 across highlighted sites. These figures reflect the reporting windows shown in the source deck.", tools="Google Business Profile, Google Ads, Meta Ads, LinkedIn and Ubersuggest", status="Measured agency work"),
    dict(slug="valentines-email-marketing-campaign", title="Valentine’s Email Marketing Campaign", category="Email Marketing", image="email-marketing.png", source="https://drive.google.com/file/d/1PvMu_5YbWdsGeJXebzClHrC4gNKsY_nC/view", summary="A seasonal email campaign concept designed to turn gifting intent into a simple mobile-first purchase journey.", problem="Brands compete heavily for attention during Valentine’s season while customers want meaningful and convenient gift options.", strategy="Combine emotional relevance, a clear offer, urgency and one direct call to action using the AIDA framework.", execution=["Defined audiences including long-distance couples, diaspora gift senders and busy professionals.", "Developed the campaign idea, offer structure, message hierarchy and mobile-friendly design direction.", "Mapped the journey from email to product page, purchase and delivery.", "Defined open-rate, click-through and conversion targets for future measurement."], result="This is a campaign concept and execution blueprint. The percentage ranges in the report are expected benchmarks, not achieved campaign results.", tools="Email strategy, AIDA copywriting, customer journey mapping, offer design and mobile-first layout", status="Campaign concept"),
    dict(slug="alibaba-youth-social-media-plan", title="Alibaba Youth Social Media Plan", category="Social Media Strategy", image="social-media-strategy.png", source="https://drive.google.com/file/d/1s6KCyjF1mgVfn6MmbkKYv747e4dKel8k/view", summary="An independent social-media planning exercise focused on younger, mobile-first and value-conscious e-commerce audiences.", problem="Large product catalogues and deal-led positioning can make it difficult to maintain relevance, trust and consistent engagement with younger shoppers.", strategy="Use platform-specific short video, creator partnerships, interactive content and time-sensitive offers to connect affordability with entertainment.", execution=["Reviewed brand position, audience behavior and the competitive context.", "Defined Instagram, X and YouTube roles.", "Proposed short videos, influencer partnerships, polls, challenges and flash-sale content.", "Created example content themes, KPIs, a calendar and budget framework."], result="The project is an academic or portfolio strategy exercise. Its reach, click and conversion figures are proposed targets rather than verified campaign outcomes.", tools="Audience analysis, SWOT, social-channel planning, content calendar and KPI design", status="Independent strategy case study"),
    dict(slug="christopher-john-rogers-launch-campaign", title="Christopher John Rogers Collection Launch Campaign", category="Integrated Marketing Campaign", image="cjr-campaign.png", source="https://drive.google.com/file/d/1R6PDWsLwMjabyK4lxtrgC7IVqHJc8bvb/view", summary="An independent integrated campaign plan connecting social media, paid advertising, email acquisition and e-commerce conversion for a fashion collection launch.", problem="A collection launch needs coordinated awareness, audience growth, email capture and purchase pathways rather than disconnected promotional posts.", strategy="Build phased awareness, engagement and conversion across Instagram, Facebook, email and the website, supported by audience segmentation and retargeting.", execution=["Defined campaign objectives and a measurement framework.", "Planned influencer content, teaser reels, behind-the-scenes content, carousel ads and retargeting.", "Designed list-building routes through social profiles, website forms and lead ads.", "Structured email flows for existing customers and new prospects, including message-testing concepts."], result="This portfolio project presents campaign targets and a testing approach. Except where clearly described as an illustrative A/B insight, the KPIs are planning targets and not verified commercial outcomes.", tools="Meta campaign planning, Mailchimp, GA4 measurement design, segmentation and A/B testing", status="Independent campaign plan"),
    dict(slug="hotfro-africa-digital-strategy", title="Hotfro Africa Digital Marketing Strategy", category="Digital Growth Strategy", image="hotfro-strategy.png", source="https://drive.google.com/file/d/1NqdKzItIs7qgp2Oeg6zZjfDV38JW62Z5/view", summary="A 90-day digital growth system for a Ghanaian natural-haircare brand, connecting education, proof, products, social content, WhatsApp and a conversion-focused website.", problem="The audit identified inconsistent posting, limited storytelling and proof, underused educational content, weak conversion pathways and an inactive website link.", strategy="Use educational and trust-building content to drive qualified audiences into a simple WhatsApp-led sales journey supported by a functioning landing page.", execution=["Defined priority audiences, pain points and commercial objectives.", "Created content pillars across education, customer proof, products and lifestyle.", "Proposed a mobile-first website and direct WhatsApp action.", "Developed content-volume, inquiry, traffic and conversion targets for a 90-day programme."], result="The strategy includes target outcomes for reach, engagement, enquiries, sales and website conversion. These are planning targets, not presented as verified results.", tools="Digital audit, content strategy, Meta Ads planning, WhatsApp conversion and landing-page planning", status="Strategy and prototype"),
    dict(slug="wonderbuild-ai-search-visibility", title="Wonderbuild AI Search Visibility Strategy", category="SEO, AEO and Lead Generation", image="wonderbuild-strategy.png", source="https://drive.google.com/file/d/1xVKV5hlnWTqA2gIx8IxpMl4-uzH5u55X/view?usp=sharing", summary="A digital strategy for a Ghanaian interlocking-brick company combining website improvement, SEO, AI search visibility, authority content and lead generation.", problem="The audit found low social visibility, inconsistent posting, limited proof, weak calls to action, missing WhatsApp integration and an underused leadership voice.", strategy="Connect Facebook awareness, LinkedIn authority and a search-optimized website to a clear enquiry and site-visit funnel.", execution=["Audited Facebook, LinkedIn and the website journey.", "Defined audiences across contractors, developers, architects, engineers, property owners, government and NGOs.", "Planned educational content, project showcases, testimonials and leadership commentary.", "Introduced SEO targeting, WhatsApp conversion, paid lead generation and website improvements."], result="The project reports that Wonderbuild appeared in a Google AI Overview, providing an early visibility signal. The broader enquiry and order figures are targets for a three-month programme, not confirmed results.", tools="SEO, AEO, website optimization, LinkedIn strategy, Meta Ads and lead-funnel design", status="Strategy with early search-visibility evidence"),
    dict(slug="customer-support-ticket-classifier", title="Customer Support Ticket Classifier", category="Machine Learning and NLP", image="ticket-classifier.png", source="https://drive.google.com/file/d/10s-vys4CH6mRaxJ2DyopS5U7I0863bWP/view", summary="An NLP system designed to classify support tickets automatically and reduce manual routing work.", problem="Manual ticket sorting can be slow and inconsistent, making prioritization and response management difficult.", strategy="Build a reproducible text-classification pipeline, compare it with a simple majority baseline, and expose predictions through a user-friendly application.", execution=["Cleaned and prepared noisy ticket text.", "Explored category distributions and text patterns.", "Built a TF-IDF and logistic-regression baseline and designed a stronger contextual modeling path.", "Created deployment architecture, a prediction interface and a CI/CD workflow."], result="The project report records a 19.2% majority-class baseline and approximately 95% accuracy for the TF-IDF logistic-regression model on its evaluation split. Production readiness would still require class-level metrics, leakage checks, drift monitoring and testing on unseen operational data.", tools="Python, NLP, TF-IDF, logistic regression, transformer experimentation, FastAPI, Gradio, Docker and CI/CD", status="Working ML prototype"),
    dict(slug="loan-default-prediction-platform", title="Loan Default Prediction Platform", category="Machine Learning and Fintech", image="loan-default.png", source="https://drive.google.com/file/d/1pjS-jRuG3klNJvXDZCwyh2rgajRzKZ6o/view", summary="A machine-learning prototype for estimating loan-default risk through an interactive decision-support interface.", problem="Manual credit-risk assessment may be slow, inconsistent and difficult to scale across digital lending workflows.", strategy="Use a classification model to generate a risk probability while presenting performance and limitations transparently to a human decision-maker.", execution=["Prepared applicant data and trained classification models.", "Reviewed discrimination through ROC analysis and errors through a confusion matrix.", "Built a Streamlit interface for interactive assessment.", "Defined future work around explainability, API integration and monitored deployment."], result="The source deck reports 87.5% accuracy, 85% precision, 90% recall and an 87% F1 score on its evaluation setup. These figures need reproducible validation, fairness review and out-of-sample testing before the model could support real lending decisions.", tools="Python, scikit-learn, Pandas, NumPy and Streamlit", status="Portfolio ML prototype"),
    dict(slug="movie-recommendation-system", title="Movie Recommendation System", category="Machine Learning and Recommender Systems", image="movie-recommendation.png", source="https://drive.google.com/file/d/1vWzzqeDzIKIJ4LUND-O2atzEJY8KZnTp/view", summary="A content-based recommendation prototype that suggests similar films using movie metadata.", problem="Large catalogues make discovery difficult, while ordinary search may not surface titles with similar themes, genres or creative attributes.", strategy="Represent selected movie metadata as vectors and use cosine similarity to retrieve the most similar titles without requiring personal viewing history.", execution=["Merged the TMDB 5000 Movies and Credits datasets.", "Prepared overview, genre, keyword, cast and director features.", "Used vectorization and cosine similarity to rank related movies.", "Built a Streamlit interface that returns five recommendations from a selected title."], result="The prototype demonstrates a clear content-based workflow. Its recommendations were not evaluated through live user behavior, and future work could add collaborative or hybrid filtering, ratings and a broader catalogue.", tools="Python, Pandas, CountVectorizer, cosine similarity, TMDB datasets and Streamlit", status="Working recommendation prototype"),
    dict(slug="itn-usage-prediction-dashboard", title="ITN Usage Prediction Dashboard", category="Public Health Machine Learning", image="itn-prediction.png", source="https://drive.google.com/file/d/12cdQ5J3BW4WYl4S9ih3M7Kwra20MRBKU/view?usp=sharing", summary="A malaria-prevention dashboard exploring predicted insecticide-treated net use, risk segmentation, trends and intervention scenarios.", problem="ITN distribution does not guarantee use, while retrospective reporting offers limited support for targeting behavioral and access interventions.", strategy="Combine survey-data processing, classification, risk segmentation and what-if scenarios in one decision-support dashboard.", execution=["Designed automated data ingestion and dynamic column mapping.", "Explored demographic, education and access features linked with reported ITN use.", "Compared classification approaches including logistic regression and random forest.", "Added risk segments, trend views and intervention-simulation concepts."], result="The application demonstrates how survey data could support programme planning. Predictions require external validation, representative data, bias review and public-health interpretation before operational use.", tools="Python, Pandas, scikit-learn, classification modeling and Streamlit", status="Public health ML prototype"),
    dict(slug="post-caesarean-pain-analytics", title="Post-Caesarean Pain Prediction and Analytics", category="Maternal Health Analytics", image="post-cs-pain.png", source="https://drive.google.com/file/d/17oTAyOc-tpwGM9voWDw83mts8WIv9u3s/view?usp=sharing", summary="A research-support application for collecting, analyzing and exploring the risk of moderate-to-severe pain after caesarean section.", problem="Manual analysis can slow research and make it harder to combine data entry, visualization and exploratory prediction in one accessible workflow.", strategy="Create a simple research dashboard that accepts common data formats, summarizes patterns and demonstrates an interpretable prediction workflow.", execution=["Designed upload support for CSV, Excel and form-derived datasets.", "Created tables and charts for pain patterns and patient characteristics.", "Added an exploratory risk-prediction component.", "Deployed a Streamlit-based interface intended for research demonstration."], result="The application is a research prototype and does not provide a clinical diagnosis or treatment recommendation. Clinical use would require a defined dataset, protocol, external validation, safety review and institutional approval.", tools="Python, data analysis, visualization, Streamlit, GitHub and cloud deployment", status="Research-support prototype"),
    dict(slug="surveilai-outbreak-reporting-system", title="SurveilAI District Outbreak Reporting System", category="Public Health Informatics", image="surveilai.png", source="https://drive.google.com/file/d/1wTOkCHyHFKTg5dksPB5yCTQSXc_F_SXm/view?usp=sharing", summary="A district-level prototype for case capture, unique identifiers, dashboard summaries and exportable surveillance records.", problem="Paper-based and fragmented reporting can delay information flow from facilities to district teams and limit timely analysis.", strategy="Provide one lightweight workflow for structured case capture, automatic identifiers, real-time summaries and export for further review.", execution=["Built a case-reporting form with entry and onset dates and demographic fields.", "Added automatic case IDs and live counters.", "Created summary analytics and CSV export.", "Defined future extensions for databases, alerts, GIS, APIs and machine-learning signals."], result="The prototype demonstrates a faster digital workflow, but it does not prove earlier outbreak detection or improved response outcomes. The current source describes CSV storage and future rather than completed DHIMS2 integration.", tools="Python, Streamlit, Pandas, CSV storage, GitHub and Streamlit Cloud", status="Early surveillance prototype"),
    dict(slug="giphep-public-health-emergency-platform", title="GIPHEP Public Health Emergency Platform", category="UI/UX and Public Health Systems", image="giphep.png", source="https://drive.google.com/file/d/1wmx2wlVoSpviLpB-nCMLoFGWUZn9mQFr/view", summary="A UI/UX concept for a national public-health emergency intelligence suite supporting surveillance, risk assessment and coordinated response.", problem="Fragmented systems, delayed data flow and the absence of a shared operational picture can weaken coordination during public-health emergencies.", strategy="Design a tiered platform concept connecting data ingestion, analysis, alerts, dashboards and coordinated response views.", execution=["Mapped challenges from detection through response.", "Designed concepts for hotspot detection, alerts, system integration and a central dashboard.", "Outlined district, regional and national access levels.", "Included privacy, audit, explainability and data-sovereignty requirements in the design brief."], result="GIPHEP is a product and interface concept, not a deployed national system. Security, standards alignment, governance and impact statements in the deck are design requirements or expected benefits that require implementation and independent verification.", tools="UX research, workflow mapping, information architecture, dashboard design and responsible-AI planning", status="UI/UX concept"),
    dict(slug="ai-nutrition-ghana-dashboard", title="AI Nutrition Ghana Dashboard", category="UI/UX and Nutrition Analytics", image="ai-nutrition-dashboard.png", source="https://drive.google.com/file/d/1SqFWvSkY8-qgEynFxUJ2RzHy673V0Hks/view", summary="A UI/UX case study for automating questionnaire analysis and presenting nutrition-behavior and AI-adoption patterns.", problem="Manual questionnaire processing is time-consuming and may delay interpretation of demographic and nutrition-behavior patterns.", strategy="Design an upload-to-insight workflow that makes distributions, cross-tabulations and correlations accessible to researchers and nutrition professionals.", execution=["Mapped the workflow from upload through processing, analysis and visualization.", "Designed demographic, AI-usage and correlation views.", "Included exportable reports and cross-tabulation concepts.", "Proposed a full-stack architecture and future extensions for prediction, scheduled imports, multilingual support and field collection."], result="The case study uses AI-generated example data that must be replaced or verified before analysis. It is a UI/UX and product concept, not evidence of a validated nutrition surveillance platform.", tools="UI/UX design, React concept, Node.js concept, Python analytics, PostgreSQL concept, D3.js and Chart.js", status="UI/UX concept with prototype architecture"),
]

STYLE = """.project-actions{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.project-actions a{padding:12px 18px;border-radius:10px;background:#0a7c82;color:#fff;text-decoration:none;font-weight:800}.project-actions a.secondary{background:#fff;color:#0a7c82;border:1px solid #b9d9d9}.badge{display:inline-block;padding:7px 11px;border-radius:999px;background:#fff3d8;color:#915500;font-weight:800}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:24px 0}.facts div{padding:18px;border:1px solid #dbe8e2;border-radius:14px;background:#f7fbf9}.facts strong{display:block;color:#0a7c82;margin-bottom:6px}@media(max-width:760px){.facts{grid-template-columns:1fr}}"""

def list_items(items):
    return "".join(f"<li>{escape(item)}</li>" for item in items)

def page(p):
    canonical = f"{BASE}/insights/{p['slug']}.html"
    image = f"{BASE}/assets/insights/projects/{p['image']}"
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(p['title'])} | Ebenezer Kwaw</title>
<meta name="description" content="{escape(p['summary'])}"><link rel="canonical" href="{canonical}">
<link rel="stylesheet" href="../assets/insights.css"><meta property="og:type" content="article"><meta property="og:title" content="{escape(p['title'])}"><meta property="og:description" content="{escape(p['summary'])}"><meta property="og:image" content="{image}"><meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"Article","headline":"{escape(p['title'])}","author":{{"@type":"Person","name":"Ebenezer Kwaw"}},"datePublished":"2026-09-25","articleSection":"{escape(p['category'])}"}}</script><style>{STYLE}</style></head>
<body class="feature-article"><header class="topbar"><nav class="nav container"><a class="brand" href="../"><span>EK</span>Ebenezer Kwaw</a><div class="navlinks"><a href="../#about">About</a><a href="../#impact">Impact</a><a href="./">Insights</a><a href="../#contact">Contact</a></div></nav></header>
<main><header class="article-hero"><div class="container article-hero-grid"><div class="article-hero-copy"><p class="eyebrow">{escape(p['category'])} · Project Case Study</p><h1>{escape(p['title'])}</h1><div class="article-meta">By Ebenezer Kwaw · 25 September 2026 · <span class="badge">{escape(p['status'])}</span></div><div class="project-actions"><a href="{p['source']}" target="_blank" rel="noopener">{escape(p.get('source_label', 'View original report'))} ↗</a><a class="secondary" href="https://kwaw-ebn.github.io/Ebenezer-Kwaw-portfolio/#projects" target="_blank" rel="noopener">View portfolio ↗</a></div></div><div class="article-hero-media"><img src="../assets/insights/projects/{p['image']}" alt="{escape(p['title'])} project preview" loading="eager"></div></div></header>
<article class="article"><p class="lead">{escape(p['summary'])}</p>
<div class="facts"><div><strong>Project type</strong>{escape(p['status'])}</div><div><strong>Discipline</strong>{escape(p['category'])}</div><div><strong>Primary evidence</strong>{escape(p.get('evidence', 'Original project report retained on Google Drive'))}</div></div>
<h2>The challenge</h2><p>{escape(p['problem'])}</p>
<h2>The strategy</h2><p>{escape(p['strategy'])}</p>
<h2>My contribution and execution</h2><ul>{list_items(p['execution'])}</ul>
<h2>Tools and methods</h2><p>{escape(p['tools'])}</p>
<h2>Outcome, evidence and limitations</h2><p>{escape(p['result'])}</p>
<aside class="article-callout"><strong>Portfolio evidence note</strong><p>This page distinguishes implemented work, measured results, proposed targets and future ideas. The original report remains available for context and visual evidence.</p></aside>
<h2>Why this project matters</h2><p>This project demonstrates how I translate a practical problem into a structured strategy, prototype or analytical workflow. It also records the limits of the current work and the next validation needed before broader use.</p>
<div class="project-actions"><a href="{p['source']}" target="_blank" rel="noopener">{escape(p.get('source_label', 'Open original report'))} ↗</a><a class="secondary" href="./">Explore more insights →</a></div>
<div class="author-box"><p><strong>Ebenezer Kwaw</strong><br>Public health, data, artificial intelligence and digital innovation professional based in Ghana.</p></div><a class="back" href="./">← Back to all insights</a></article></main>
<footer class="footer"><div class="container"><span>© 2026 Ebenezer Kwaw</span><span>Public Health · Data · Digital Innovation</span></div></footer></body></html>'''

for project in PROJECTS:
    (OUT / f"{project['slug']}.html").write_text(page(project), encoding="utf-8")

cards = []
for i, project in enumerate(PROJECTS, start=11):
    cards.append(f'''<a class="card" href="{project['slug']}.html">
<img class="card-image" src="../assets/insights/projects/{project['image']}" alt="{escape(project['title'])} project preview" loading="lazy">
<span class="number">{i:02d} · {escape(project['category'])} · Case Study</span>
<h2>{escape(project['title'])}</h2>
<p>{escape(project['summary'])}</p>
<span class="read">Read case study →</span>
</a>''')

def replace_generated_block(path, start, end, content):
    text = path.read_text(encoding="utf-8")
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    path.write_text(before + start + "\n" + content + "\n" + end + after, encoding="utf-8")

replace_generated_block(
    OUT / "index.html",
    "<!-- PORTFOLIO_CASE_STUDIES_START -->",
    "<!-- PORTFOLIO_CASE_STUDIES_END -->",
    "\n".join(cards),
)

sitemap_urls = "\n".join(
    f'  <url><loc>{BASE}/insights/{project["slug"]}.html</loc><changefreq>monthly</changefreq><priority>0.7</priority></url>'
    for project in PROJECTS
)
replace_generated_block(
    ROOT / "sitemap.xml",
    "<!-- PORTFOLIO_CASE_STUDIES_START -->",
    "<!-- PORTFOLIO_CASE_STUDIES_END -->",
    sitemap_urls,
)
